service: apollo-lambda
provider:
  name: aws
  runtime: nodejs16.x
  region: ${opt:region, "us-east-1"}
  httpApi:
    cors: true
package:
  patterns:
    - schema.graphql
functions:
  graphql:
    handler: src/server.graphqlHandler
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET
plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-plugin-typescript
